stages:
  - image
  - build-test
  - release

variables:
  CONTAINER_TEST_IMAGE: bmxnet-v2/build.ubuntu_cpu:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: bmxnet-v2/build.ubuntu_cpu:latest

build_docker_image:
  stage: image
  image: docker:stable
  before_script:
    - docker info
  script:
    - cd ci
    - docker build -f docker/Dockerfile.build.ubuntu_cpu --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 --cache-from bmxnet-v2/build.ubuntu_cpu -t $CONTAINER_TEST_IMAGE docker

build_and_test:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build-test
  image: $CONTAINER_TEST_IMAGE
  before_script:
    - ls && pwd
    - export PYTHONPATH=./python/
    - export MXNET_MKLDNN_DEBUG=1  # Ignored if not present
    - export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
    - python --version
  script:
    - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_DIST_KVSTORE=1 -j$(nproc)
    - pytest tests/python/unittest/test_binary.py

release-image:
  stage: release
  image: docker:stable
  script:
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  only:
    - master
